- redirects.json
* fixes a Marketo bug as this file was removed, but still needed
* I updated the Marketo template so new files do not require this.
> add icon-social.svg redirect

- templates/about/index.html
Corrected broken links on the /about page.
Got to `/about` and ensure that the "News ›" link near the bottom of the page doesn't 404.
> update insights news link

- static/js/scratch.js
- templates/index.html
As the first step to replacing all JavaScript that depends on YUI, I'm removing the homeAnimation function.
I don't understand why it's needed. All it seems to do is add the "run" class to the "animation" element,
which is the same as just including it in the markup in the first place.
I imagine I'm missing something, someone please enlighten me.
QA
--
Run the site (`make run`) and check the homepage animation still works.
> Remove core.homeAnimation

- static/js/core.js
- static/js/polyfills.js
- templates/_base/base.html
As a basis for starting the work of rewriting all JavaScript the depends on YUI, I am:
- Creating a new `core.js` file to house new core site JavaScript (following the pattern of www.ubuntu.com)
- I'll migrate the existing functions into `core.js` as they're rewritten to remove YUI
- Add polyfills to support development in plain JavaScript, allowing us to use modern methods with backards compatability (like www.ubuntu.com)
I will now propose 1 pull-request per JavaScript function that I re-write, but I will base them all off this one, which provides the basic infrastructure.
QA
---
Run the site (`make run`) and check nothing has changed.
> Remove yui: basis

- static/js/scratch.js
scratch.js is only loaded inside an `[if gte IE 9]` conditional, and its really only <=IE8 which have SVG problems. Also, the SVG fallback script as it stands would be broken anyway, as it simply replaces `svg` with `png`, which doesn't work for the new assets server. I used [netrenderer](https://netrenderer.com/index.php) to confirm that no images show up properly on the live site.
Also, on ubuntu.com, IE8 now makes up 0.3% of our traffic (3.37% use IE, of which 8.24% is IE8). I'm gonna assume canonical.com is similar, so I don't think we should worry about it.
Therefore I think there's no point to the SVG fallback and it should be removed.
QA
---
Check you agree with me.
Run the site, click around check there are no JS errors.
For extra credits, check the whole site in IE8 against how …
> Remove SVG fallback

- static/css/section/_about.scss
- static/css/styles.scss
- static/js/scratch.js
This function was only setting the `html.yes-js` class, which is redundant since Modernizr sets `.js`.
QA
---
Run the site (`make run`), and check, first with JavaScript that:
- The HTML element has a `js` class, and doesn't have a `no-js` class
- The map on <http://127.0.0.1:8002/about> displays fine (and looks the same as live)
Then without JavaScript:
- The HTML element has a `no-js` class, and no `js` class
- <http://127.0.0.1:8002/about> shows the "Where we are" row (and looks the same as live)
> Remove core.setupHtmlClass

- .gitignore
- requirements/standard.txt
- static/js/scratch.js
- templates/partners/index.html
- webapp/lib/feeds.py
- webapp/templatetags/feeds.py
Port over the server-side feed solution from www.ubuntu.com,
and use that to replace uses of the `loadPartners` script.
QA
---
Run the site (`make run`). Browse to <http://127.0.0.1:8002/partners> and check both logo clouds load properly.
For extra credits, check these only contain partners that are in the correct filter in the partners website.
> Remove YUI: Remove loadPartners

- static/js/scratch.js
- templates/_includes/vacancies.html
- templates/careers/all-design-and-user-experience-vacancies.html
- templates/careers/all-marketing-and-business-development-vacancies.html
- templates/careers/all-operations-vacancies.html
- templates/careers/all-professional-services-vacancies.html
- templates/careers/all-technical-and-engineering-vacancies.html
- templates/careers/all-vacancies.html
- templates/careers/cloud-vacancies.html
- templates/careers/go-vacancies.html
- templates/careers/index.html
Use `get_rss_feed` instead of rssLoader.
Also, stop using stmgrts.org.uk feed mirror, just use feeds direct from taleo.
QA
--
Run site (`make run`).
Go to <http://127.0.0.1:8002/careers/>, and all <http://127.0.0.1:8002/careers/*-vacancies> pages, and check all feeds load properly and show correct jobs.
> Remove YUI: Replace rssLoader with server-side feeds

- static/js/core.js
- static/js/scratch.js
- static/js/utilities.js
- templates/_base/base.html
**Please review & merge #105 first**
- Use plain JS
- USe localStorage over cookies
- Move to `core.js`
QA
---
```
make run
```
Go to <http://127.0.0.1:8002/> (or any other page) and check you see the cookie notification. Click the cross, check it goes away.
Reload the page or browse around the site, check it's still gone.
To reset back to check again, you need to remove the `cookiePolicyAccepted` key from localStorage. In chrome developer tools, do this under:
`Application -> Local Storage -> http://127.0.0.1:8002 -> {right click on cookiePolicyAccepted} -> delete`
> Rewrite core.cookiePolicy to remove YUI

- static/js/core.js
- static/js/scratch.js
- templates/about/index.html
- templates/careers/index.html
**Please review and merge #105 first**
- Replace YUI with plain JavaScript
- Move to core.js
- Call the function from the bottom of each page that needs it
I've also removed the `tabbedContent` function and the `accordion-button` elements.
Since they weren't even visible on the existing pages, I'm guessing they're from a byegone era and so are no longer needed. **Please correct me if I'm wrong**.
QA
--
```
make run
```
Go to <http://www.canonical.com/careers> and <http://www.canonical.com/about> and check the "tabbed" sections still work as they do on live.
> Remove YUI: Replace sectionTabs with new setupTabs

- static/js/core.js
- static/js/scratch.js
- templates/projects/index.html
**Please review & merge #105 first**
- Create `core.js` (following the www.ubuntu.com pattern), to house new JavaScript and eventually decommission `scratch.js`
- Add polyfills for new plain ES^ JavaScript work
- Rewrite `core.setupAccordion` and move it to `core.js`
- For clarity, call `core.setupAccordion` from `projects/index.html` rather than calling it when the JavaScript file is loaded
QA
---
```
make run
```
Visit <http://127.0.0.1:8002/projects> and check all product descriptions expand and collapse as expected.
> Rewrite core.setupAccordion to remove YUI

- templates/careers/all-design-and-user-experience-vacancies.html
- templates/careers/all-marketing-and-business-development-vacancies.html
- templates/careers/all-operations-vacancies.html
- templates/careers/all-professional-services-vacancies.html
- templates/careers/all-technical-and-engineering-vacancies.html
- templates/careers/all-vacancies.html
- templates/careers/cloud-vacancies.html
- templates/careers/go-vacancies.html
- templates/careers/index.html
- templates/careers/vacancies_contextual_footer.html
Most taleo links currently follow 2 redirects and eventually end up on ldd.tbe.taleo.net.
This is inefficient, but more importantly it makes it much more complicated to allow these requests through the firewall.
So I'm updating all these to point to their eventual targets.
QA
---
Go through each page on the `/careers` section and check that all feeds look correct and that all links to search for jobs still work.
> Update all taleo links

- templates/404.html
- templates/500.html
Updated the URLs to report bugs on the 404 and 500 error pages.
View /404 and /500 and see the updated links.
Also note that they are now, correctly, external links.
Fixes #121
> update the error pages' links to point to github

- webapp/settings.py
Detect if the site is running https by checking the 'HTTP_X_FORWARDED_PROTO' header. This is set in our mojo deploy settings.
This setting is currently working correctly with assets manager
> Add proxy SSL detection

- templates/about/index.html
Added details of the Texas office to the Google Map on /about
- Pull down code
- Navigate to /about
- Click the Google marker on Texas and check that the correct address displays: 
```
Austin, USA
Canonical USA Inc. 
Link Flex 
2301 W Anderson Ln 
Austin, TX 78757
USA
```
https://trello.com/c/WEukghyO
> Add Texas office to Google map on /about

- static/css/section/_partners.scss
Update the partners image strip with a new MWC image
- Go to `/partners`
- Scroll to the MWC image strip
- Check the file size isn't too large (<200kb)
- Check the image scales with the screen width
Fixes https://github.com/canonical-websites/www.canonical.com/issues/123
> Update partners management image

- static/css/section/_home.scss
- templates/careers/all-design-and-user-experience-vacancies.html
- templates/careers/all-marketing-and-business-development-vacancies.html
- templates/careers/all-operations-vacancies.html
- templates/careers/all-professional-services-vacancies.html
- templates/careers/all-technical-and-engineering-vacancies.html
- templates/careers/all-vacancies.html
- templates/index.html
- templates/partners/index.html
- templates/products/index.html
- templates/projects/index.html
* updated the homepage text and images
* updated the projects page
* updated the partners' text and images
* updated the projects page
* updated the careers references
*see that the images have to mobile devices - ALL PAGES BELOW*
1. go to / and see that the copy matches the [copy doc](https://docs.google.com/document/d/1WcNN2RlQQrbLSP5ZgcIsAeQAHj5h_yDW6Yd5oBMmU3M/edit#)
2. go to /products and see the copy matches the [copy doc](https://docs.google.com/document/d/1-PY9w_BtCGS9CkSJqTKjOCkSzmgvROxfk-BcwitFEcE/edit)
3. go to /partners and see the copy matches the [copy doc](https://docs.google.com/document/d/1O7rMRIcRVINNsoiJ5fUQ4FPqUxGDKB3E6AaPZU2BAmc/edit#)
4. go to the vacancies pages and see they do not mention mobile
[demo website](http://www.canonical.com-remove-mobile.demo.haus/)
> Remove mobile

- static/sass/styles.scss
- templates/_base/base.html
Canonical logo should link to home
- Pull code
- View http://0.0.0.0:8002/about
- Click logo in top left
- Browser should return to http://0.0.0.0:8002/
Fixes #189
> Canonical logo should link to home

- static/sass/custom/_lightbulb-animation.scss
Removed margin-top from all elements of the animation.
- Pull down this code
- Run `./run`
- Go to http://0.0.0.0:8002/
- Check that the light bulb is aligned correctly
Fixes https://github.com/canonical-websites/www.canonical.com/issues/182
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/81
> Align the homepage lightbulb animation

- templates/about/index.html
- templates/partners/index.html
- templates/services/index.html
Fix the wrapping external links in the contextual footers. I believe the changed layout looks nicer too.
- Pull down code
- Run `./run`
- Go to http://0.0.0.0:8002/about
- Go to http://0.0.0.0:8002/partners
- Go to http://0.0.0.0:8002/services
- Scroll to the footers and check the external icons don't wrap
Fixes https://github.com/canonical-websites/www.canonical.com/issues/184
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/82
> Fix the wrapping external links in the contextual footers

- package.json
- static/sass/styles.scss
- yarn.lock
Update Vanilla framework to v1.5.1 and remove the brochure include.
- Pull this code
- Run `./run clean`
- Run `./run`
- Go to http://0.0.0.0:8002/
- Check the site and make sure there is nothing broken
> Update Vanilla framework to v1.5.1

- bower.json
Updated the cookie policy dep to the latest version. Solving the issue that cookie policy is not closeable on iPhones.
- Pull down this branch
- Run `./run clean`
- Run `./run`
- Check that the output contains `bower canonical-cookie-policy#^1.0.2`
- Go to http://0.0.0.0:8002/
- Check the cookie policy works (you may need to delete the `_cookie_accepted` cookie using your browers inspector
> Update the cookie policy dependency to v1.0.2

- templates/products/index.html
- Corrected the location of the cloud and ubuntu icons on the 'Canonical and Ubuntu' banner
- Check that the cloud icon is in the third column and ubuntu icon is in the fourth
Fixes #212
> Switched locations for cloud and ubuntu icons on products page

- templates/about/map.html
* Zoomed out google map on /about page to show all our offices better
1. get this branch
2. `./run` the site
3. look at [about page](http://0.0.0.0:8002/about)
Fixes #217
> Zoomed out google map on /about page

- templates/products/index.html
* Removed suffix-1 from two columns of text on /products in the ‘On the client: devops for IoT’ section as it looked unbalanced
- download the branch
- `./run` the site
- look at [product page](http://0.0.0.0:8002/products)
> Removed suffix-1 from two columns of text on /products

- templates/about/index.html
- templates/about/map.html
* Removed the Boston office from the /about page map
3. View the site locally in your web browser at: [about page](http://0.0.0.0:8002/about) and see there is no Boston office
Fixes #230
> Removed the Boston office from the /about page map

- templates/about/index.html
Removed Anand from the exec section of the about page
3. View the site locally in your web browser at: [http://0.0.0.0:8002/about](http://0.0.0.0:8002/about)
4. Scroll to "Our management team" section
5. Check Anand is not there.
Fixes https://github.com/canonical-websites/www.canonical.com/issues/233#issuecomment-357247830
> Remove Anand from executives in the about page

- static/sass/styles.scss
- templates/_base/footer.html
- Add contact link to footer
4. Look at the footer on any page and make sure the contact us link/button is there
[Fixes #245](https://app.zenhub.com/workspace/o/canonical-websites/www.canonical.com/issues/245)
> Add contact link to footer

- templates/services/index.html
- yarn.lock
Fix typos on services page
3. View the site locally in your web browser at: <http://0.0.0.0:8002/services>
4. Check that typos referenced in issue description have been removed
Fixes #241
> Fix typos on services page

- templates/_base/footer.html
Update copyright notice in footer
4. Make sure the footer copyright notice is: " © 2018 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd."
[Fixes #235](https://app.zenhub.com/workspace/o/canonical-websites/www.canonical.com/issues/235)
> Update copyright notice in footer

- requirements.txt
Gunicorn 19.7.1 creates an error in our deployment from a bug when using
the `--umask=0` flag. Locking to the previous verison avoids this bug.
( Reference https://github.com/benoitc/gunicorn/issues/1622 )
- `./run build` - Just to update requirements
- `./run exec -p 8002 "gunicorn webapp.wsgi --umask=0"`
Server should start up ~but the port isn't forwarded so the site isn't visible~
> Pin Gunicorn to 19.7.0 to avoid umask error

- static/sass/_pattern_link.scss
- static/sass/styles.scss
- templates/_base/base.html
- templates/about/index.html
- templates/partners/index.html
- templates/services/index.html
- Removed bespoke css that has been solved with the new spacing
- Fixed navigation logo alignment
- Fixed heading external link vertical alignment
- Fixed center-aligned muted headings
- Fixed numbering on the stepped list in /services
- Check out this feature branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8002/
- Check that the logo is center-aligned in the nav, not top-aligned
- Go to /careers/all-vacancies and check that the external link icons are aligned properly in the section headers
- Go to /services and check that the muted headings are centered
- Also check that the stepped list is numbered properly
Fixes vanilla-framework/vanilla-framework#1726
Fixes vanilla-framework/vanilla-framework#1728
Fixes …
> Bespoke styling fixes for Vanilla 1.7.0-beta

- templates/projects/directory.html
- Update the projects/directory page
- Some whitespace appears, but only candid changed
- Check out this feature branch
- Run the site using the command `./run serve`
- View the site locally in your web browser at: http://0.0.0.0:8002/projects/directory
- compare to the [spreadsheet](https://docs.google.com/spreadsheets/d/14Smfpq9ttrPt2jPx70NB3QTixH_6h7Ktnp1CihjT1So/edit#gid=0)
Fixes #267
> Update the projects/directory page

- package.json
- static/sass/styles.scss
- yarn.lock
Update Vanilla framework to v1.6.7
4. Check the site looks "better" than the live site
Fixes https://github.com/canonical-websites/www.canonical.com/issues/269
> Update Vanilla framework to v1.6.7

- templates/_includes/extended-footer.html
- templates/about/index.html
- templates/services/index.html
- webapp/templatetags/utils.py
Renamed insights to blog
4. Check that links in footer have been updated from insights to blog
Fixes [#514](https://github.com/ubuntudesign/web-squad/issues/514)
> Rename insights to blog

- package.json
- templates/_includes/extended-footer.html
- templates/about/index.html
- templates/services/index.html
- webapp/templatetags/utils.py
- yarn.lock
- Bump global nav version
4. Make sure navigation has a blog link and not an insights link
Fixes [#512](https://github.com/ubuntudesign/web-squad/issues/512)
> Bump global nav version

- static/sass/custom/_inline-ubuntu-logo.scss
- Fix alignment of logo image in 'We deliver Ubuntu' heading
4. Check that the Ubuntu logo in the 'We deliver Ubuntu' heading is baseline aligned
Fixes [#278](https://github.com/canonical-websites/www.canonical.com/issues/278)
> Fix alignment of logo in a heading

- templates/_includes/extended-footer.html
Make all the links in the extended footer the same colour
4. See the footer lists links are all the same colour (blue)
Fixes #201 
[if relevant, include a screenshot]
> Make all footer links the same colour

- templates/about/map.html
* had to use the google maps with an api key, which is locked to this domain
3. View the site locally in your web browser at: [http://localhost:8002/about](http://localhost:8002/about)
4. see that the map works
Fixes #292
> update map to use google api key

- templates/about/index.html
- templates/about/map.html
* Added the Boston office to the /about map
3. View the site locally in your web browser at: [http://localhost:8002/about](http://localhost:8002/about)
4. See that the Boston office has a marker and a card when you click on it.
5. See that it hides when you click on another marker
_Note, the map api might not work on the demo_
Fixes #295
> Add Boston office

- webapp/views.py
Add new lines to views.py to fix:
```
./webapp/views.py:10:1: E302 expected 2 blank lines, found 1
./webapp/views.py:17:1: E302 expected 2 blank lines, found 1
```
The CI tests should pass correctly with this PR.
> Fix lint error in views.py

- templates/products/index.html
- “verticals” > “industries” (more polite)
- “the all snap version of Ubuntu” > “the all-snap version of Ubuntu” (hyphenates pre-noun adjective phrase)
- “enterprises, government, educational institutions” > “enterprises, governments, educational institutions” (uses plurals consistently)
- “Canonical works with most of the world’s PC makers, to” > Canonical works with most of the world’s PC makers to” (drops unmatched clause marker)
- “ease to use” > “easy-to-use” (hyphenates pre-noun adjective phrase)
> Copyedits “Products” page

- templates/_includes/extended-footer.html
- templates/about/index.html
* Removed google plus from the footer and about page
3. View the site locally in your web browser at: [http://0.0.0.0:8002/](http://0.0.0.0:8002/) and [about](http://0.0.0.0:8002/about)
4. See that there is no google+ link
Fixes #311
footer
about
> Removed google plus from the footer and about page

- requirements.txt
Fixes GitHub's security alert for https://nvd.nist.gov/vuln/detail/CVE-2018-14574
(Although this vulnerability didn't actually effect us, as we don't use `APPEND_SLASH = True`)
Qa
--
`./run` the site, thoroughly check it still works, especially complex parts like the careers feed.
> Upgrade to Django 1.11.16

- package.json
- yarn.lock
Updated to Vanilla 1.8
Note: there is a bug in 1.8 where borders are missing on strips that are followed by strips with a background. This is fixed in Vanilla master, which will be released in v2.0. We should leaving this minor issue in place to avoid adding hacks.
4. Compare with live and ensure that the site looks the same (or better)
> Update Vanilla to v1.8

- requirements.txt
Github flagged this as a security vulnerability.
* Updated Python dep 'requests' as recommended by Github to include security patch. 
4. Verify site runs without errors and all tests pass.
Fixes #316
> Update requests python dep

- templates/_base/footer.html
Change year in the footer to 2019
4. Make sure the current year is displayed in the footer.
Fixes #358
> Change year to 2019 and to update automatically

- entrypoint
- requirements.txt
- webapp/wsgi.py
* Move from gevent to sync workers
* Add service name in logs
4. Make sure we get `service=canonical.com` inlogs
> Move from gevent to sync workers

- templates/partners/contact-us.html
- templates/services/contact-us.html
* added google recaptcha to canonical.com forms
3. View the site locally in your web browser at: http://0.0.0.0:8002/services/contact-us and http://0.0.0.0:8002/partners/contact-us
4. See that the recaptcha form is there and the form submits
> Add google recaptcha to forms
