canonical-web-and-design/www.canonical.com

templates/_base/footer.html
Updated the site footer to link to the github repo
Check that the link is correct
Fixes #91
=> update the footer bug link to github, not launchpad

templates/projects/directory.html
Updated the content of the project directory
Check /projects/directory against the highlighted edits in https://docs.google.com/spreadsheets/d/11vdgbyW_nce48y-cHTnhwiJd804b9PIslsO03w8HF5E/edit?ts=57ae0046#gid=0
=> update of project directory content

static/js/scratch.js, templates/_includes/article-items.html, templates/about/index.html
QA
--
Go to `/about`, check news and resources feeds at the bottom of the page show up as on live.
=> Replace getInsightsFeed with back-end feeds

templates/projects/index.html
Updated the hero image on /projects to an SVG
- Pull down the branch
- Run `make run`
- Go to http://127.0.0.1:8002/projects
- Check the heart hero image is an SVG now
Fixes https://github.com/canonical-websites/www.canonical.com/issues/20
=> Make the heart hero image an SVG

README.md
added pip install -r requirements/dev.txt command
=> add pip requirements

README.md
it was not helpful and already in the docker setup.
=> removing pip command I added earlier

templates/about/index.html
* updated www.canonical.com/about per Udi's [request](https://docs.google.com/document/d/17OdwH3Rqb5Nq_6o--yP3ukC6WPaazNZ5BlJxQiZkJvw/edit?ts=59282873#) 
* updated the [copy doc](https://docs.google.com/document/d/1O3KUX41hwsehnAedYV5Pp4i_aMrKDTGYiri5uR6N9fc/edit)
* run locally and confirm text update looks ok
* look at the [demo](http://www.canonical.com-update-public-clouds.demo.haus/about)
=> update list of public clouds per Udi

static/sass/section/_about.scss, templates/about/index.html
Updated the membership and details of the management team.
- Pull this branch
- Run `./run`
- Go to http://0.0.0.0:8002/about
- You may need to remove the feeds to stop an error
- Scroll down to Our management team section
- Check the details match the docs:
https://docs.google.com/spreadsheets/d/1hbYKnud_p5VLK1eNX6fX2PUDX_uFWuVlA_vJxugLk6s/edit#gid=0
Fixes #145 
http://www.canonical.com-update-our-management-team.demo.haus/about
=> Update our management team section

templates/about/index.html
Upadted the Beijing office address on the map
- `./run`
- View the [about page](http://localhost:8002/about)
- Click on the Beijing map pin
- See that the content matches the requested update on #162 
Fixes #162
=> Update Beijing office address

bower.json, package.json, static/sass/styles.scss, templates/_base/base.html, templates/_includes/article-items.html, templates/about/index.html, templates/about/map.html, templates/careers/index.html, yarn.lock
See design review: https://github.com/ubuntudesign/vanilla-squad/issues/58
- Pull code
- Check http://0.0.0.0:8002/about against checklist above
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/58
=> Design feedback on /about

static/sass/styles.scss, templates/products/index.html
Addressed design checklist at: https://github.com/ubuntudesign/vanilla-squad/issues/53
- Pull code
- Verify against checklist above
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/53
=> Design feedback on /products

templates/partners/index.html
Address feedback in https://github.com/ubuntudesign/vanilla-squad/issues/55
- Pull code
- Check http://0.0.0.0:8002/partners against the checklist above
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/55
=> Action design feedback on /partners

static/sass/styles.scss, templates/projects/directory.html, templates/projects/index.html
Address feedback in https://github.com/ubuntudesign/vanilla-squad/issues/54
- Pull code
- Check http://0.0.0.0:8002/projects and http://0.0.0.0:8002/projects/directory against the checklist above
Fixes https://github.com/ubuntudesign/vanilla-squad/issues/54
=> Design feedback for /projects

templates/projects/index.html
Add dividing lines to contextual footer on /projects
- Run `./run serve`
- Check http://0.0.0.0:8002/projects
- Verify contextual footer has dividing lines
Fixes #187
=> Add dividing lines to contextual footer on /projects

static/sass/styles.scss
Ensure logo on hover does not have white bg
- Run code
- Visit http://0.0.0.0:8002/
- Roll over logo and verify a white background does not appear
Fixes #190
=> Ensure logo on hover does not have white bg

templates/projects/directory.html
* updated the /project/directory with new projects and people
* updated the [spreadsheet](https://docs.google.com/a/canonical.com/spreadsheets/d/14Smfpq9ttrPt2jPx70NB3QTixH_6h7Ktnp1CihjT1So/edit?usp=sharing) that drives this
* download branch, run the server and look at the [directory page](http://0.0.0.0:8002/projects/directory)
* compare to the spreadsheet
=> update to the directory of opensource projects

templates/about/index.html, templates/about/map.html
Update the Japan office address on the map and add the address on small screens.
- Pull the code
- Run `./run`
- Go to http://0.0.0.0:8002/about
- Check that the map pop up content is correct
- Check that the small screen text is correct
Fixes https://github.com/canonical-websites/www.canonical.com/issues/197
=> Update the Japan office address

templates/about/index.html, templates/about/map.html
Added the Japan office's phone number.
- Pull this branch
- Run `./run`
- Go to /about
- Check the map data has the new Japan address and phone number
- Check on small screens is also correct
Fixes https://github.com/canonical-websites/www.ubuntu.com/issues/2240
=> Add Japan phone number

templates/about/index.html, templates/projects/directory.html, templates/projects/index.html, templates/services/index.html
- Added footers to /services, /projects, /projects/directory and /about
- Styled the footers similar to index.html (alternating p-strip--light, adding borders etc.)
- Check the footers exist and that they are styled appropriately
Fixes #200
=> Added footers to req pages as well as styling similar to index.html

templates/about/index.html
- Updated Anan's bio on /about page
- Check that Anan's title and bio are up to date with the web changes doc
Fixes #208
=> Updated Anan's bio

templates/projects/directory.html
Typo fix
https://en.wikipedia.org/wiki/Deprecation
https://www.canonical.com/projects/directory
=> project directory: fix deprecated typo

static/sass/custom/_ubuntu-eco-system-animation.scss
Lined the images in the animation on the /products
Go to the [products page](http://localhost:8002/products)
See that the images in the hero animation are properly arranged.
Fixes #183
=> Update the animation elements to line up correctly

templates/projects/directory.html, templates/services/index.html
* Updated Azure logo per Microsoft’s request
* Drive-by - replaced Alejandra Obregon’s name on the project directory
* run the site
* look at these pages: [services](http://0.0.0.0:8002/services) and [directory](http://0.0.0.0:8002/projects/directory)
=> Updated Azure logo

.github/PULL_REQUEST_TEMPLATE.md
* Updated pull request template to have more QA details
- just read it
=> Updated pull request template to have more QA details

templates/services/index.html
* Balanced the layout on /services in the ‘What happens when you engage us?’ section
* Updated the copy to better fix the layout
* Centred the muted heading
* Re-indented the code
1. download this branch
2. `./run` the server
3. look at [services page](http://0.0.0.0:8002/services)
4. compare to the [copy doc](https://docs.google.com/document/d/1LZf4CH6S8LHG5kAGaoDNbXjvfzVfCMHAyGTy-Qs0Mcs/edit#)
=> Balanced the layout on /services

package.json, static/sass/styles.scss, templates/_base/base.html, yarn.lock
Updated the Vanilla dependency to v1.6.3. Removed fixes that have landed upstream and added a fix for the new max-width.
4. Click through the pages and check it looks the same as live.
Fixes https://github.com/vanilla-framework/vanilla-framework/issues/1461
=> Update to Vanilla v1.6.3

.gitignore
=> Add __init__.py to templatetags

templates/partners/index.html
* Updated spelling of Arm from ARM
3. View the site locally in your web browser at: [partners](http://0.0.0.0:8002/partners)
Fixes [u.c bug 2571](https://github.com/canonical-websites/www.ubuntu.com/issues/2571)
=> Updated spelling of Arm from ARM

templates/about/index.html
* Remove Mike Bell from about page
[Fixes #239](https://app.zenhub.com/workspace/o/canonical-websites/www.canonical.com/issues/239)
=> Remove Mike Bell from about section

package.json
Update global nav
4. Check that clicking 'ubuntu' in the global nav goes to ubuntu.com
[Fixes #235](https://app.zenhub.com/workspace/o/canonical-websites/insights.ubuntu.com/issues/235)
=> Update global nav

package.json, static/sass/_pattern_link.scss, static/sass/styles.scss, templates/_base/base.html, templates/about/index.html, templates/index.html, templates/partners/index.html, templates/products/index.html, templates/services/index.html, yarn.lock
- Updated site to Vanilla 1.7.0 and removed bespoke css where possible
- Check that the site looks good and is using Vanilla v1.7.0
=> Update to Vanilla 1.7.0

templates/index.html
Change homepage laptop image
4. Check laptop image on homepage matches supplied image
Fixes #276
=> Change homepage laptop image

templates/products/index.html
Update image on `/products`
3. View the site locally in your web browser at: <http://0.0.0.0:8002/products>
4. See that the laptop image matches the one supplied in the issue
Fixes #282
=> Update image on products page

templates/partners/index.html
Update image on `/partners`
3. View the site locally in your web browser at: <http://0.0.0.0:8002/partners>
4. See that the laptop image matches the one supplied
Fixes #283
=> Update image on partners page

templates/projects/directory.html
https://en.wiktionary.org/wiki/deprecate#Usage_notes
=> Fix typo: “depriciated” → “deprecated”

requirements.txt
Fixes #313
QA
--
`./run` and check the site runs fine
=> Use compatible talisker and prometheus versions

templates/products/index.html
Fixes #322
Look at the demo, go to https://www-canonical-com-canonical-websites-pr-323.run.demo.haus/products, see the laptop image loads quicker than it does on live.
=> Reduce image to 800 pixels

templates/_base/footer.html
=> Copyright 2019

package.json, yarn.lock
* Add resolutions for critical vulnerabilities
4. Ensure no errors
=> Add resolutions for critical vulnerabilities

README.md
Updates Readme for rewrite of the webpage in https://github.com/canonical-web-and-design/canonical.com
=> Adds note for canonical rewrite

templates/projects/directory.html
* Update project directory
3. View the site locally in your web browser at: http://0.0.0.0:8002/projects/directory
4. Compare to the [copy sheet](https://docs.google.com/spreadsheets/d/14Smfpq9ttrPt2jPx70NB3QTixH_6h7Ktnp1CihjT1So/edit#gid=0)
Fixes #366
=> Update project directory

webapp/views.py
* Updated the metadata index for greenhouse as we exposed more fields
3. View the site locally in your web browser at: http://0.0.0.0:8002/careers/all-vacancies
4. See that the list is sorted by department
=> Update metadata index for greenhouse
